[package]
name = "matrixcompare"
version = "0.1.0"
authors = ["Andreas Longva"]
edition = "2018"

[dependencies]
num = "0.2"
matrixcompare-core = { path = "matrixcompare-core", version="0.1"}

[dev-dependencies]
quickcheck = "0.8.3"
matrixcompare-mock = { path = "matrixcompare-mock", version="0.1" }
proptest = "0.9"