[package]
name = "matrixcompare"
version = "0.1.0"
authors = ["Andreas Longva"]
edition = "2018"

[dependencies]
num = "0.2"

[dev-dependencies]
quickcheck = "0.8.3"
matrixcompare-mock = { path = "matrixcompare-mock" }
proptest = "0.9"