[package]
name = "matrixcompare-core"
version = "0.1.0"
authors = ["Andreas Longva"]
edition = "2018"
license = "MIT"
repository = "https://github.com/Andlon/matrixcompare"
keywords = [ "matrix", "comparison", "linear algebra" ]
description = "Core traits for matrixcompare"

[dependencies]
