[package]
name = "matrixcompare-mock"
version = "0.1.0"
authors = ["Andreas Longva <andreas.b.longva@gmail.com>"]
edition = "2018"

[dependencies]
num = "0.2"
matrixcompare = { path = "..", version="0.1" }
proptest = "0.10"

