[package]
name = "matrixcompare-mock"
version = "0.1.0"
authors = ["Andreas Longva"]
edition = "2018"
license = "MIT"
repository = "https://github.com/Andlon/matrixcompare"

[dependencies]
num = "0.2"
matrixcompare = { path = "..", version="0.1" }
proptest = "0.10"

